services:
  # Servicio para la Base de Datos
  mysqldb:
    image: mysql:8.0
    container_name: muebleria_db
    environment:
      MYSQL_DATABASE: muebleria_db
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s # Agregado para dar margen en el primer arranque
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/db/muebleria_db.sql:/docker-entrypoint-initdb.d/init.sql

  # Servicios para el Backend
  backend:
    build: ./backend
    container_name: muebleria_backend
    ports:
      - "8080:8080"
    depends_on:
      mysqldb:  # <--- CORREGIDO: Usamos el nombre del servicio, SIN guion
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/muebleria_db?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  # Servicios para el Frontend 
  frontend:
    build: ./frontend
    container_name: muebleria_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data: